export const FETCH_SONGS_REQUEST = 'FETCH_SONGS_REQUEST';
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';
export const FETCH_SONGS_FAILURE = 'FETCH_SONGS_FAILURE';

export const TOGGLE_PLAY = 'TOGGLE_PLAY';
export const PLAY_SONG = 'PLAY_SONG';
export const PLAY_PREVIOUS = 'PLAY_PREVIOUS';
export const PLAY_NEXT = 'PLAY_NEXT';
